// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzgybqhuykwshpslrinq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6Z3licWh1eWt3c2hwc2xyaW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODExNTUsImV4cCI6MjA3MjU1NzE1NX0.oSAq65sloZzxHPuqNBUJCVhMS09V05GstjVJQubPSWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});